maintainer        "Patrick Galbraith"
maintainer_email  "patg@patg.net"
license           "Apache 2.0"
description       "Installs Percona client and server, builds cluster"
version           "0.0.1"
supports          "ubuntu"
depends           "build-essential"
depends           "apt"
depends           "python"
